flaskblog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')

flaskblog/main/routes.py
from flask import Blueprint
from flask import render_template, request, flash
from flaskblog.models import Post
from flask_login import login_required
from flaskblog.posts.forms import PostForm
from flaskblog.bpsRest import *
import paramiko
from subprocess import check_output
import re

main = Blueprint('main', __name__)

bpspassword = 'cyberland123'


def launchBpsAttack(attackName):
    bps = BPS('172.16.14.28', 'admin', bpspassword)
    bps.login()
    # login
    # showing current port reservation state
    bps.portsState()
    # reserving the ports.
    bps.reservePorts(slot=1, portList=[0, 1, 2, 3], group=1, force=True)
    # running the canned test 'AppSim' using group 1
    # please note the runid generated. It will be used for many more functionalities
    runid = bps.runTest(modelname=attackName, group=1)
    # showing progress and current statistics
    progress = 0
    while (progress < 100):
        progress = bps.getRTS(runid)
        time.sleep(1)
    # showing the test result (Pass/Fail)
    # a sleep is put here because we do not immediately get the test results.
    # inserting a sleep to allow for the data to be stored in the database before retrieval
    time.sleep(1)
    bps.getTestResult(runid)

    # logging out
    bps.logout()


@main.route("/attack/apt1", methods=['GET', 'POST'])
@login_required
def apt1():
    form = PostForm()
    launchBpsAttack("Victor-Zeus-CNC-Sourcefire")
    time.sleep(1)
    launchBpsAttack("Victor-SSH-DLP-Attack")

    flash('Your APT 1 has been launched!', 'success')

    return render_template('apt.html', title='test', form=form)


@main.route("/attack/apt2", methods=['GET', 'POST'])
@login_required
def apt2():
    form = PostForm()
    launchBpsAttack("Victor-ESA-Bad-Keyword")
    time.sleep(1)
    launchBpsAttack("Victor-Virus-Web-Site")  # Changed
    time.sleep(1)
    launchBpsAttack("Victor-Malware-ZPACK")

    flash('Your APT 2 has been launched!', 'success')

    return render_template('apt.html', title='test', form=form)


@main.route("/attack/apt3", methods=['GET', 'POST'])
@login_required
def apt3():
    form = PostForm()
    launchBpsAttack("Victor-Web-Attack")
    time.sleep(1)
    launchBpsAttack("Victor-ESA-Credit-Card")
    time.sleep(1)
    launchBpsAttack("Victor-IRC-DLP")

    flash('Your APT 3 has been launched!', 'success')

    return render_template('apt.html', title='test', form=form)


@main.route("/attack/apt4", methods=['GET', 'POST'])
@login_required
def apt4():
    form = PostForm()
    launchBpsAttack("Victor-Adobe-Malware-Server-Client")
    time.sleep(1)
    launchBpsAttack("Victor-SMB-DLP-Attack")

    flash('Your APT 4 has been launched!', 'success')

    return render_template('apt.html', title='test', form=form)


@main.route("/attack/apt5", methods=['GET', 'POST'])
@login_required
def apt5():
    form = PostForm()
    launchBpsAttack("Victor-Windows-RDP-Attack")  # Changed
    time.sleep(1)
    launchBpsAttack("Victor-DataLeak-FTP")

    flash('Your APT 5 has been launched!', 'success')

    return render_template('apt.html', title='test', form=form)


@main.route("/attack/apt6", methods=['GET', 'POST'])
@login_required
def apt6():
    form = PostForm()
    launchBpsAttack("Victor-Bot-to-Botmaster-Zeus")
    time.sleep(1)
    launchBpsAttack("Victor-Botmaster-to-bot-IOS-Trojan")

    flash('Your APT 6 has been launched!', 'success')

    return render_template('apt.html', title='test', form=form)


@main.route("/attack/apt7", methods=['GET', 'POST'])
@login_required
def apt7():
    form = PostForm()
    launchBpsAttack("Victor-Ransom-Attack")
    time.sleep(1)
    launchBpsAttack("Victor-Duqu-Botnet-DLP")

    flash('Your APT 7 has been launched!', 'success')

    return render_template('apt.html', title='test', form=form)


@main.route("/attack/apt8", methods=['GET', 'POST'])
@login_required
def apt8():
    form = PostForm()
    launchBpsAttack("Victor-bash-attack")
    time.sleep(1)
    launchBpsAttack("Victor-DDOS ICMP Flood Attack")

    flash('Your APT 8 has been launched!', 'success')

    return render_template('apt.html', title='test', form=form)


@main.route("/attack/apt9", methods=['GET', 'POST'])
@login_required
def apt9():
    form = PostForm()
    launchBpsAttack("Victor-Carbanak-Attack")
    time.sleep(1)
    launchBpsAttack("Victor-DataLeak-HTTPS")

    flash('Your APT 9 has been launched!', 'success')

    return render_template('apt.html', title='test', form=form)

# This the part for the Demo Routes


@main.route("/attack/netflow_demo", methods=['GET', 'POST'])
@login_required
def netflow_demo():
    form = PostForm()
    ip = '172.16.14.38'
    port = 22
    username = 'root'
    password = 'toor'
    cmd = '/root/netflow_cnc_script.sh'

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(ip, port, username, password)

    stdin, stdout, stderr = ssh.exec_command(cmd)
    outlines = stdout.readlines()
    resp = ''.join(outlines)
    print(resp)
    flash(resp, 'success')

    return render_template('about_demo.html', title='test', form=form)

# The First Netflow Attack in Netflow Lab Guide Page


@main.route("/attack/netflow_cnc", methods=['GET', 'POST'])
@login_required
def netflow_cnc():
    form = PostForm()
    ip = '172.16.14.38'
    port = 22
    username = 'root'
    password = 'toor'
    cmd = '/root/netflow_cnc_script.sh'

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(ip, port, username, password)

    stdin, stdout, stderr = ssh.exec_command(cmd)
    outlines = stdout.readlines()
    resp = ''.join(outlines)
    print(resp)
    flash(resp, 'success')

    return render_template('netflow_labguide.html', title='test', form=form)

# The Second Netflow Attack in Netflow Lab Guide Page


@main.route("/attack/netflow_scan", methods=['GET', 'POST'])
@login_required
def netflow_scan():
    form = PostForm()
    ip = '172.16.14.38'
    port = 22
    username = 'root'
    password = 'toor'
    cmd = '/root/netflow_scan_script.sh'

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(ip, port, username, password)

    stdin, stdout, stderr = ssh.exec_command(cmd)
    outlines = stdout.readlines()
    resp = ''.join(outlines)
    print(resp)
    flash(resp, 'success')

    return render_template('netflow_labguide.html', title='test', form=form)


@main.route("/attack/threatIntel_demo", methods=['GET', 'POST'])
@login_required
def threatIntel_demo():
    form = PostForm()
    ip = '172.16.14.39'
    port = 22
    username = 'root'
    password = 'toor'
    cmd = '/root/threat_intel.sh'

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(ip, port, username, password)

    stdin, stdout, stderr = ssh.exec_command(cmd)
    outlines = stdout.readlines()
    resp = ''.join(outlines)
    print(resp)
    flash(resp, 'success')

    return render_template('about_demo.html', title='test', form=form)


@main.route("/attack/waf_attack1", methods=['GET', 'POST'])
@login_required
def waf_attack1():
    form = PostForm()
    ip = '172.16.14.38'
    port = 22
    username = 'root'
    password = 'toor'
    cmd = '/root/wap/wap_case1.sh'

    ssh = paramiko.SSHClient()
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    ssh.connect(ip, port, username, password)

    stdin, stdout, stderr = ssh.exec_command(cmd)
    outlines = stdout.readlines()
    resp = ''.join(outlines)
    print(resp)
    flash(resp, 'success')

    return render_template('about_demo.html', title='test', form=form)


@main.route("/attack/cl_bps_demo", methods=['GET', 'POST'])
@login_required
def cl_bps_demo():
    form = PostForm()
#    flash('Your attack has been started!', 'success')
    bps = BPS('172.16.14.28', 'admin', bpspassword)
    bps.login()
    # login
    # showing current port reservation state
    bps.portsState()
    # reserving the ports.
    bps.reservePorts(slot=1, portList=[0, 1, 2, 3], group=1, force=True)
    # running the canned test 'AppSim' using group 1
    # please note the runid generated. It will be used for many more functionalities
    # runid = bps.runTest(modelname='Victor-ESA-Test-Spam', group=1)
    # showing progress and current statistics
    # progress = 0
    # try:
    #     while (progress < 100):
    #         progress = bps.getRTS(runid)
    #         time.sleep(1)
    # except:
    #     print("An exception occurred")
    # showing the test result (Pass/Fail)
    # a sleep is put here because we do not immediately get the test results.
    # inserting a sleep to allow for the data to be stored in the database before retrieval
    # time.sleep(1)
    # bps.getTestResult(runid)
    # progress = 100
    # print('start')

    # print('end')

    # Second test: Steve-WebSec-Test
    # runid = bps.runTest(modelname='Steve-WebSec-Test', group=1)
    # showing progress and current statistics
    # progress = 0
    # try:
    #     while (progress < 100):
    #         progress = bps.getRTS(runid)
    #         time.sleep(1)
    # except:
    #     print("An exception occurred")
    # showing the test result (Pass/Fail)
    # a sleep is put here because we do not immediately get the test results.
    # inserting a sleep to allow for the data to be stored in the database before retrieval
    # time.sleep(2)
    # bps.getTestResult(runid)

    # Second Test
    runid = bps.runTest(modelname='Victor-Malware-Hash-Test', group=1)
    # showing progress and current statistics
    progress = 0
    try:
        while (progress < 100):
            progress = bps.getRTS(runid)
            time.sleep(1)
    except:
        print("An exception occurred")
    # showing the test result (Pass/Fail)
    # a sleep is put here because we do not immediately get the test results.
    # inserting a sleep to allow for the data to be stored in the database before retrieval
    time.sleep(10)

flaskblog/posts/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request, abort
from flask_login import current_user, login_required
from flaskblog import db
from flaskblog.models import Post
from flaskblog.posts.forms import PostForm

posts = Blueprint('posts', __name__)


@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author=current_user)
        db.session.add(post)
        db.session.commit()
        flash('Your post has been created!', 'success')
        return redirect(url_for('main.home'))
    return render_template('create_post.html', title='New Post', form=form, legend='New Post')


@posts.route("/post/<int:post_id>")
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)


@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', form=form, legend='Update Post')


@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('main.home'))

flaskblog/users/routes.py
from flask import Blueprint
from flask import render_template, url_for, flash, redirect, request
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog import db, bcrypt
from flaskblog.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from flaskblog.users.utils import save_picture, send_reset_email
from flaskblog.models import User, Post

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()

        flash(f'Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title='Register', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account', image_file=image_file, form=form)


@users.route("/user/<string:username>")
def user_posts(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)

    return render_template('user_posts.html', posts=posts, user=user)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('This is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()

        flash(f'Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

flaskblog/templates/about_demo.html
{% extends "layout.html" %}
{% block content %}
    <h1>Attack Demo Page:</h1>
    <p>
        <a class="btn btn-primary btn-xs" href="{{ url_for('main.netflow_demo') }}">1. Demo - Netflow</a>
    </p>
    <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('threatIntel').innerHTML =
        '<h6><font color=white>ThreatIntel starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.threatIntel_demo') }}">
        2. Demo - Threat Intel</a>
        <div class="badge badge-danger text-wrap" style="width: 36rem; height: 2rem;"  id="threatIntel"></div>
    </p>

    <p>
	    <a class="btn btn-primary btn-xs" href="{{ url_for('main.attack6') }}">3. Demo - Windows Brute</a>
    </p>
    <p>
        <a class="btn btn-primary btn-xs" href="{{ url_for('main.waf_attack1') }}">4. Demo - WAF ATTACK1</a>
    </p>
    <p>
	    <a class="btn btn-primary btn-xs" onclick="document.getElementById('demo1').innerHTML = '<h6><font color=white>Attack 1 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.cl_bps_demo') }}">5. Demo - CL</a>
	    <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="demo1"></div>
	</p>

{% endblock content %}

flaskblog/templates/apt.html
{% extends "layout.html" %}
{% block content %}
    <h1>APT Attack Page:</h1>
   <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('apt1').innerHTML =
        '<h6><font color=white>APT1 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.apt1') }}">
        APT1 - Zeus CNC Sourcefire</a>
        <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="apt1"></div>
    </p>

   <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('apt2').innerHTML =
        '<h6><font color=white>APT2 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.apt2') }}">
        APT2 - ESA-WSA-ZPACK</a>
        <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="apt2"></div>
    </p>

   <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('apt3').innerHTML =
        '<h6><font color=white>APT3 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.apt3') }}">
        APT3 - Web-ESA-IRC-DLP</a>
        <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="apt3"></div>
    </p>

    <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('apt4').innerHTML =
        '<h6><font color=white>APT4 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.apt4') }}">
        APT4 - Adobe-Malware-SMB-DLP</a>
        <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="apt4"></div>
    </p>

    <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('apt5').innerHTML =
        '<h6><font color=white>APT5 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.apt5') }}">
        APT5 - Synful-Knock-FTP-DLP</a>
        <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="apt5"></div>
    </p>

    <p>
        <a class="btn btn-primary btn-xs" href="{{ url_for('main.apt6') }}">APT6 - Zeus-CNC-Sourcefire-Trojan</a>
    </p>

    <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('apt6').innerHTML =
        '<h6><font color=white>APT6 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.apt6') }}">
        APT6 - Zeus-CNC-Sourcefire-Trojan</a>
        <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="apt6"></div>
    </p>

    <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('apt7').innerHTML =
        '<h6><font color=white>APT7 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.apt7') }}">APT7 - Ransom-Dataleak-HTTP</a>
        <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="apt7"></div>
    </p>

    <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('apt8').innerHTML =
        '<h6><font color=white>APT8 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.apt8') }}">APT8 - Bash-ICMP-Flood</a>
        <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="apt8"></div>
    </p>

    <p>
        <a class="btn btn-primary btn-xs" onclick="document.getElementById('apt9').innerHTML =
        '<h6><font color=white>APT9 starts launching......Please do not close this page!</font></h6>';" href="{{ url_for('main.apt9') }}">APT9 - Carbanak-Malware-Dataleak-HTTPS</a>
        <div class="badge badge-danger text-wrap" style="width: 28rem; height: 2rem;"  id="apt9"></div>
    </p>



{% endblock content %}

flaskblog/templates/firewall_labguide.html
{% extends "layout.html" %}
{% block content %}
    <h1>Firewall Lab Guide Page:</h1>
    <p>
        <a class="btn btn-primary btn-xs" href="{{ url_for('main.firewall_syn_flood') }}">1. SYN Flood Attack</a>
    </p>
    <p>
        <a class="btn btn-primary btn-xs" href="{{ url_for('main.firewall_ddos') }}">2. DDoS Attack</a>
    </p>
    <p>
        <a class="btn btn-primary btn-xs" href="{{ url_for('main.firewall_packetcapture') }}">3. Packet Capture</a>
    </p>

{% endblock content %}

flaskblog/templates/home.html
{% extends "layout.html" %}
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
              <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" href="{{ url_for('posts.post', post_id=post.id) }}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
    {% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
      {% if page_num %}
        {% if posts.page == page_num %}
          <a class="btn btn-info mb-2" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
          <a class="btn btn-outline-info mb-2" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
      {% else %}
        ...
      {% endif %}
    {% endfor %}
{% endblock content %}

flaskblog/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}

            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div>
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div>
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                </div>
                <div>
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            <small class="text-muted ml-2">
                <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>

    </div>
{% endblock content %}

flaskblog/templates/netflow_labguide.html
{% extends "layout.html" %}
{% block content %}
    <h1>Netflow Lab Guide Page:</h1>
    <p>
        <a class="btn btn-primary btn-xs" href="{{ url_for('main.netflow_cnc') }}">1. Netflow CNC</a>
    </p>
    <p>
	    <a class="btn btn-primary btn-xs" href="{{ url_for('main.netflow_scan') }}">2. Neflow Scan</a>
    </p>

{% endblock content %}

flaskblog/templates/post.html
{% extends "layout.html" %}
{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.author.image_file) }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="{{ url_for('users.user_posts', username=post.author.username) }}">{{ post.author.username }}</a>
        <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
        {% if post.author == current_user %}
         <div>
           <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id) }}">Update</a>
           <button type="button" class="btn btn-danger btn-sm m-1" data-toggle="modal" data-target="#deleteModal">Delete</button>
         </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ post.title }}</h2>
      <p class="article-content">{{ post.content }}</p>
    </div>
  </article>
  <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.delete_post', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}